name: ggev3dgs
channels:
  - defaults
  - nvidia
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - cuda-cccl=12.9.27=0
  - cuda-cccl_linux-64=12.9.27=0
  - cuda-cudart=12.9.79=0
  - cuda-cudart-dev=11.7.99=0
  - cuda-cudart_linux-64=12.9.79=0
  - cuda-nvcc=11.7.99=0
  - cuda-version=12.9=3
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.23=he99959a_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py39h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - alembic==1.16.5
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - colorlog==6.9.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - fonttools==4.60.1
      - greenlet==3.2.4
      - h5py==3.14.0
      - idna==3.4
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - joblib==1.5.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - llvmlite==0.43.0
      - lpips==0.1.4
      - mako==1.3.10
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - narwhals==2.7.0
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.26.4
      - opencv-python==4.8.0.74
      - optuna==4.5.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==9.3.0
      - plotly==6.3.1
      - plyfile==1.1.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.28.1
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - six==1.17.0
      - sqlalchemy==2.0.44
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - tomli==2.3.0
      - torch==1.13.1+cu117
      - torchvision==0.14.1+cu117
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==1.26.13
      - uv==0.8.22
      - zipp==3.23.0
prefix: /root/miniconda3/envs/ggev3dgs
